






INSERT INTO nk3mek0vtopbdoh.new (img, title, txt_1, gal, txt_2) VALUES ('img_app/nk3mek0vtopbdoh/2021-lamborghini-huracan-sto-102-1640358040.jpg', 'Lamborghini Hurac?n STO Is Primed for Attack', 'The remoras are back. Drive a car like a Lamborghini Hurac?n STO on the freeway and a school of hangers-on forms around it. Booting the 631-hp 5.2-liter V-10 shakes them only temporarily. Emboldened by the knowledge that Officer Bob Speed is far more likely to pay attention to a Lamborghini than a Dodge Charger, they quickly race back into position.', '["img_app/nk3mek0vtopbdoh/2021-lamborghini-huracan-sto-107-1640358038.jpg"," img_app/nk3mek0vtopbdoh/2021-lamborghini-huracan-sto-108-1640358038.jpg"," img_app/nk3mek0vtopbdoh/2021-lamborghini-huracan-sto-112-1640358044.jpg"," img_app/nk3mek0vtopbdoh/2021-lamborghini-huracan-sto-113-1640358043.jpg"," img_app/nk3mek0vtopbdoh/2021-lamborghini-huracan-sto-122-1640358049.jpg"]', 'To permanently lose traffic, head to any twisting canyon road, where there isn''t much that can keep up with a well-driven STO. Front-end grip inspires confidence, and the steering reads you the road like it's story time. Efforts build and release, and this wild-child car that looks like it'll dig its teeth into you proves easy to push deeper and deeper into corners. On a very dusty skidpad, we recorded 1.14 g's of cling with the optional Bridgestone Potenza Race rubber. These new street-legal track tires relinquish grip predictably and remain grippy as laps accumulate. A less extreme Potenza Sport will also be offered.')

















